Dockerfile
pkg/http/api/base_handler.go
pkg/http/api/v1/handler.go
pkg/model/harbor/model.go

feat: Implement GetMetadata handler

---

pkg/http/api/v1/handler.go

feat: Implement GetScanReport handler

---

pkg/http/api/v1/handler.go
pkg/model/transformer.go

chore: Upgrade trivy executable to 0.1.6

---

Dockerfile
README.md
cmd/scanner-trivy/main.go
kube/harbor-scanner-trivy.yaml
pkg/etc/config.go
pkg/etc/config_test.go
pkg/http/api/v1/handler.go

feat: Add liveness and readiness probes

---

README.md
cmd/scanner-trivy/main.go
kube/harbor-scanner-trivy.yaml
pkg/etc/config.go
pkg/http/api/server.go

feat: Add support for TLS

---

.goreleaser.yml
Dockerfile
Makefile
kube/harbor-scanner-trivy.yaml
pkg/etc/config.go
pkg/etc/config_test.go
pkg/http/api/v1/handler_test.go
pkg/model/transformer_test.go
pkg/trivy/wrapper.go
test/component/component_test.go
test/integration/api/rest_api_test.go

chore: Build Docker image based on Trivy image

---

Makefile
cmd/scanner-trivy/main.go
pkg/http/api/v1/handler.go
pkg/http/api/v1/handler_test.go
pkg/mock/store.go
pkg/persistence/redis/store.go
pkg/persistence/store.go
pkg/queue/enqueuer.go
pkg/queue/worker.go
pkg/scan/controller.go
test/integration/api/rest_api_test.go
test/integration/persistence/redis/store_test.go

The main change here is that we set TTL for scan jobs in Queued and Pending states, not only Failed or Finished.

refactor: Redis persistence store

---

.gitignore
README.md
kube/harbor-scanner-trivy.yaml
pkg/etc/config.go
pkg/etc/config_test.go
pkg/trivy/wrapper.go
pkg/trivy/wrapper_test.go
test/component/component_test.go

Merging report to single ScanReport
Update Trivy to 0.2.1
Fixes #59

Scanning also libraries

---

README.md
helm/harbor-scanner-trivy/README.md
helm/harbor-scanner-trivy/templates/secret.yaml
helm/harbor-scanner-trivy/templates/statefulset.yaml
helm/harbor-scanner-trivy/values.yaml
pkg/etc/config.go
pkg/etc/config_test.go
pkg/http/api/v1/handler.go
pkg/trivy/wrapper.go
pkg/trivy/wrapper_test.go

feat: Pass --skip-update flag to trivy executable

---

.travis.yml
Makefile
README.md
cmd/scanner-trivy/main.go
pkg/etc/config_test.go
pkg/http/api/server.go

This change is required for Harbor 2.0 https://github.com/goharbor/harbor/issues/11583

feat: Configure the minimum version of TLS to 1.2

---

.travis.yml
Makefile
README.md
cmd/scanner-trivy/main.go
go.mod
pkg/etc/checker.go
pkg/etc/checker_test.go
pkg/harbor/model_test.go
pkg/queue/worker.go

In this PR I'm adding some logs to troubleshoot FS access rights issues cause by invalid config or volume mounts
Also bumping up Go from 1.13 to 1.14

feat: Check read/write access to configurable cache and reports directories

---

Dockerfile
pkg/trivy/model.go
pkg/trivy/model_test.go

fix: Handle gracefully scratch and slim images

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/README.md
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.10.0

---

.github/workflows/build.yml
.github/workflows/release.yml
.goreleaser.yml
NOTICE
README.md

chore: Migrate from Travis CI to GitHub Actions

---

Dockerfile

chore: Bump up Trivy to v0.9.0

---

.goreleaser.yml
README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.11.0

---

README.md

docs: Update deployment docs for Harbor 2.0

---

.github/workflows/build.yml
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.12.0

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.13.0

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml
pkg/scan/transformer_test.go

release: Prepare v0.14.0

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/templates/statefulset.yaml

feat(helm): Do not automount service account token

---

.github/workflows/build.yml
go.mod
go.sum

chore: Pin Go to 1.14.7

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.14.1

---

Dockerfile
test/component/component_test.go

chore: Bump up Trivy to v0.13.0

---

.github/workflows/build.yml
.github/workflows/release.yml
go.mod

chore: Upgrade to Go 1.15

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.15.0

---

pkg/etc/config.go
pkg/etc/config_test.go

feat(config): Enable Trivy debug mode when log level is set to debug

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.16.0

---

.github/workflows/build.yml
README.md
docs/RELEASES.md

chore: Switch to main branch

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.16.1

---

.github/workflows/release.yml
Makefile
cmd/scanner-trivy/main.go
go.mod
go.sum
pkg/ext/ambassador_mock.go
pkg/harbor/model.go
pkg/http/api/base_handler.go
pkg/http/api/v1/handler.go
pkg/http/api/v1/handler_test.go
pkg/scan/transformer.go
pkg/scan/transformer_test.go
pkg/trivy/model.go
pkg/trivy/model_test.go
pkg/trivy/wrapper_test.go
test/integration/api/rest_api_test.go

feat(api): Implement pluggable scanners API v1.1

---

.github/workflows/build.yml
.github/workflows/release.yml
.goreleaser.yml
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.17.0

---

.github/workflows/build.yml
pkg/scan/transformer.go
pkg/scan/transformer_test.go
pkg/trivy/model.go

feat: Use primaryURL returned by Trivy

---

Dockerfile
test/component/component_test.go

chore: Bump up Trivy from v0.14.0 to v0.16.0

---

.github/workflows/build.yml
.github/workflows/release.yml
.goreleaser.yml
NOTICE
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.18.0

---

CONTRIBUTING.md
README.md
helm/harbor-scanner-trivy/README.md

- Seperate development and installation instructions
- Describe how to build and test the adapter service with Docker
Resolves: #139

docs: Refactor contributing guide

---

README.md
helm/harbor-scanner-trivy/README.md
helm/harbor-scanner-trivy/templates/statefulset.yaml
helm/harbor-scanner-trivy/templates/trivy-ignore-policy-cm.yaml
helm/harbor-scanner-trivy/values.yaml
pkg/etc/config.go
pkg/trivy/wrapper.go
pkg/trivy/wrapper_test.go

Signed-off-by: Peter Jakobsen <pja@kvalitetsit.dk>
This is a fix for: https://github.com/aquasecurity/harbor-scanner-trivy/issues/162

Added support for SCANNER_TRIVY_IGNORE_POLICY

---

.github/workflows/build.yml
.github/workflows/release.yml
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.19.0

---

README.md
docs/RELEASES.md

docs: Add version matrix

---

helm/harbor-scanner-trivy/values.yaml

chore(helm): Do not specify resource requests and limits

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.20.0

---

.github/workflows/build.yml
.github/workflows/release.yml
go.mod
go.sum

chore(deps): Bump up Go from v1.14 to v1.16

---

Dockerfile
README.md
test/component/component_test.go

chore(deps): Bump up trivy from v0.18.3 to v0.19.2

---

Dockerfile

fix: CVE-2021-36159 and CVE-2021-3711 in container image

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.21.0

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: Add bug report template

---

.gitignore
CONTRIBUTING.md
Vagrantfile
vagrant/harbor.yml
vagrant/install-docker-ce.sh
vagrant/install-docker-compose.sh
vagrant/install-go.sh
vagrant/install-harbor.sh

docs: Update contributing guide

---

README.md

docs: Update version matrix

---

Vagrantfile
cmd/scanner-trivy/main.go
pkg/http/api/base_handler.go
pkg/http/api/base_handler_test.go
pkg/http/api/v1/handler.go
pkg/http/api/v1/handler_test.go
pkg/trivy/wrapper_test.go
test/component/component_test.go
test/component/docker/docker.go
test/component/scanner/client.go
test/integration/api/rest_api_test.go
test/integration/persistence/redis/store_test.go
vagrant/install-docker-compose.sh
vagrant/install-docker.sh

See https://github.com/goharbor/harbor/issues/15623

chore: Remove deprecated mime type application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0

---

.github/workflows/build.yml
.github/workflows/publish-helm-chart.yml
.github/workflows/release.yml
vagrant/harbor.yml

chore: Add GitHub workflow to publish Helm charts

---

CONTRIBUTING.md
README.md
Vagrantfile
helm/harbor-scanner-trivy/README.md
helm/harbor-scanner-trivy/templates/statefulset.yaml
helm/harbor-scanner-trivy/values.yaml
pkg/etc/config.go
pkg/etc/config_test.go
pkg/http/api/v1/handler.go
pkg/http/api/v1/handler_test.go
pkg/trivy/wrapper.go
pkg/trivy/wrapper_test.go
test/integration/api/rest_api_test.go
vagrant/install-harbor.sh

feat: Configure Trivy timeout

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: Prepare v0.22.0

---

.github/workflows/publish-helm-chart.yml

fix(ci): Fix link to download chart releaser

---

.github/workflows/publish-helm-chart.yml

chore(ci): Security hardening for GitHub actions

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.25.0

---

Dockerfile
pkg/trivy/wrapper.go
pkg/trivy/wrapper_test.go
test/component/component_test.go

chore(deps): bump Trivy from v0.22.0 to v0.24.2

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.26.0

---

CONTRIBUTING.md
Vagrantfile
vagrant/install-harbor.sh

chore(deps): update Harbor to v2.4.1

---

pkg/trivy/wrapper.go

feat: handle errors when getting trivy version

---

Dockerfile
test/component/component_test.go

chore(deps): bump Trivy from  v0.24.2 to v0.25.0

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.27.0

---

Dockerfile
pkg/http/api/server.go
pkg/trivy/wrapper.go
pkg/trivy/wrapper_test.go

fix: get trivy DB version

---

Dockerfile
test/component/component_test.go

chore(deps): bump Trivy from v0.25.0 to v0.26.0

---

README.md

docs: update versions matrix

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.28.0

---

go.mod
go.sum

chore(deps): upgrade redigo to v1.8.8

---

CONTRIBUTING.md
Vagrantfile
vagrant/harbor.yml
vagrant/install-harbor.sh

chore: bump Harbor v2.4.1 to v2.5.1

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.29.0

---

Dockerfile
README.md
test/component/component_test.go

chore(deps): bump Trivy from v0.28.1 to v0.29.2

---

.github/workflows/build.yml
.github/workflows/release.yml
NOTICE
README.md

chore: remove integration with CodeCov

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.0

---

helm/harbor-scanner-trivy/Chart.yaml

release: prepare-v0.30.1

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release/prepare release v0.30.2

---

Dockerfile
README.md
test/component/component_test.go

chore: bump-trivy v0.35.0

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.3

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare-v0.30.4

---

go.mod
go.sum

chore: bump-go-version

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare-v0.30.5

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare release v0.30.6

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.7

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy version-0.38.2

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.8

---

Dockerfile
README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml
test/component/component_test.go

release: prepare v0.30.10

---

.github/workflows/build.yml
.github/workflows/release.yml
go.mod

chore: bump golang version 1.20.3

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy version v0.40.0

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.11

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy 0.42.0

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.12

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy-0.43.0

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.13

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.14

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy 0.44.0

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.15

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy 0.45.0

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.16

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy 0.46.0

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.17

---

Dockerfile
test/component/component_test.go

chore: bump trivy 0.46.1

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.18

---

.github/workflows/release.yml

chore: bump go-version release

chore: bump go-version release

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy 0.48.1

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.20

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.21

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy v0.49.1

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy-0.50.1

---

helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.30.23

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.31.0

---

Dockerfile
README.md
test/component/component_test.go

chore: bump trivy-0.51.2

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.31.2

---

Dockerfile
README.md
go.mod
test/component/component_test.go

bump: golang 1.22

---

README.md
helm/harbor-scanner-trivy/Chart.yaml
helm/harbor-scanner-trivy/values.yaml

release: prepare v0.31.3
