aquasecurity/harbor-scanner-trivy

- .travis.yml
- go.mod
It compiles properly and the tests run successfully.
```
GO111MODULE=on go test -short -race -coverprofile=coverage.txt -covermode=atomic ./...
?       github.com/aquasecurity/harbor-scanner-trivy/cmd/scanner-trivy  [no test files]
ok      github.com/aquasecurity/harbor-scanner-trivy/pkg/etc    1.013s  coverage: 100.0% of statements
ok      github.com/aquasecurity/harbor-scanner-trivy/pkg/http/api       1.015s  coverage: 76.5% of statements
ok      github.com/aquasecurity/harbor-scanner-trivy/pkg/http/api/v1    1.012s  coverage: 13.2% of statements
ok      github.com/aquasecurity/harbor-scanner-trivy/pkg/model  1.011s  coverage: 0.0% of statements [no tests to run]
?       github.com/aquasecurity/harbor-scanner-trivy/pkg/model/harbor   [no test files]
? …
```
> Upgraded Go to 1.13.

- go.mod
- pkg/http/api/base_handler_test.go
- pkg/http/api/v1/handler.go
- pkg/http/api/v1/handler_test.go
- pkg/mock/expectation.go
- pkg/mock/store.go
- pkg/mock/transformer.go
- pkg/mock/wrapper.go
- pkg/model/harbor/model.go
- pkg/model/harbor/model_test.go
- pkg/model/job/model.go
- pkg/model/transformer.go
- pkg/model/transformer_test.go
- pkg/scan/controller.go
- pkg/scan/controller_test.go
- pkg/store/redis/store.go
- pkg/store/store.go
- test/component/client_test.go
- test/integration/api/rest_api_test.go
- test/integration/store/redis_store_test.go
I've added unit tests to the main flows in scanning controller.
Also I stopped persisting Trivy scan report in Redis which was redundant.
> test: Add unit tests for scanner controller

- Dockerfile
- README.md
If you want to test it, try running component tests with the default alpine:3.10.2. Instructions are in README.
Then change the image to Amazon or Distroless, e.g. gcr.io/distroless/java, and run the component test again.
> chore: Bump up Trivy from 0.1.6 to 0.1.7

- Dockerfile
- README.md
- kube/harbor-scanner-trivy.yaml
We can benefit from the prebuilt DB used by Trivy now. No need to use initContainer anymore. The initial scan is fast anyway.
> chore: Bump up Trivy to 0.2.0

- Dockerfile
Update to the last Trivy version
> chore: bump up Trivy from 0.2.0 to 0.2.1

- helm/harbor-scanner-trivy/Chart.yaml
- helm/harbor-scanner-trivy/templates/statefulset.yaml
- helm/harbor-scanner-trivy/values.yaml
Issue: https://github.com/aquasecurity/harbor-scanner-trivy/issues/69
Some fixes for the Helm chart:
- Add fsGroup and move the securityContext to podTemplateSpec (as it doesn't support fsGroup on container level). This fixes the .cache directory not being writable
- Use emptyDir for the data volume when persistency is disabled, as otherwise it's on the root filesystem which is mounted read-only due to the readOnlyRootFilesystem security context option
- Always create and mount the tmp-data emptyDir volume, this makes it possible to run without persistent volumes (emptyDir isn't persistent)
- By default, use the default storage class of the cluster
The fixes for running without persistent volumes are mainly useful for testing
> Helm fixes

- pkg/mock/wrapper.go
- pkg/model/harbor/model.go
- pkg/model/harbor/model_test.go
- pkg/scan/controller.go
- pkg/scan/controller_test.go
- pkg/trivy/wrapper.go
When people evaluate Harbor they usually do not setup TLS. This means that the scanner adapter receives scan requests with insecure registry URLs , e.g. http://core:8080. If we build the imageRef from such URL Trivy fails, because it's trying to append the https:// before fetching layers.
The solution is to set the `TRIVY_NON_SSL` env for insecure registry URLs.
> feat: Add support for scanning images from insecure registry

- Dockerfile
- helm/harbor-scanner-trivy/Chart.yaml
- helm/harbor-scanner-trivy/values.yaml
- pkg/http/api/v1/handler_test.go
- pkg/model/harbor/model.go
- pkg/scan/transformer.go
- pkg/scan/transformer_test.go
- pkg/trivy/model.go
- pkg/trivy/wrapper.go
- pkg/trivy/wrapper_test.go
- test/component/component_test.go
- test/integration/api/rest_api_test.go
In this PR:
1. Bump Trivy version in Dockerfile (from 0.4.3 to 0.5.0)
2. Bump Harbor-Scanner-Trivy version (from 0.2.3 to 0.3.0)
3. Add LayerID to both Trivy and Harbor-Scanner-Trivy specific structs, and map LayerIds during the transformation
4. Minor code-reformattings and optimizations.
I will include inline comments for some of the changes.
> Include layer ID in Vulnerabilities information

- Dockerfile
- README.md
- helm/harbor-scanner-trivy/README.md
- helm/harbor-scanner-trivy/templates/secret.yaml
- helm/harbor-scanner-trivy/templates/statefulset.yaml
- helm/harbor-scanner-trivy/values.yaml
- pkg/etc/config.go
- pkg/etc/config_test.go
- pkg/scan/transformer.go
- pkg/scan/transformer_test.go
- pkg/trivy/wrapper.go
- test/component/component_test.go
The Harbor team hit the rate limit in CI/CD env after enabling Trivy as the default scanner.
I'm passing GITHUB_TOKEN to Trivy executable as an env to increase the limit.
/cc @steven-zou @heww
> feat: Pass GITHUB_TOKEN env to Trivy

- README.md
- cmd/scanner-trivy/main.go
- helm/harbor-scanner-trivy/README.md
- helm/harbor-scanner-trivy/values.yaml
- pkg/etc/config.go
- pkg/etc/config_test.go
- pkg/http/api/v1/handler.go
- pkg/http/api/v1/handler_test.go
- test/integration/api/rest_api_test.go
We should not include the `harbor.scanner-adapter/vulnerability-database-next-update-at` in the metadata properties when the `SCANNER_TRIVY_SKIP_UPDATE` env is set to `true`.
Also this PR introduced the following:
- Changed the default value of the `SCANNER_TRIVY_VULN_TYPE` env from `os` to `os,library`
- Added metadata properties to easily check adapter's config:
- `com.github.aquasecurity.trivy.debugMode`
- `com.github.aquasecurity.trivy.ignoreUnfixed`
- `com.github.aquasecurity.trivy.severity`
- `com.github.aquasecurity.trivy.skipUpdate`
- `com.github.aquasecurity.trivy.vulnType`
/cc @simar7
> fix: Do not show next-update-at property in metadata when we skip DB updates

- pkg/http/api/v1/handler.go
- pkg/http/api/v1/handler_test.go
- pkg/trivy/model.go
- pkg/trivy/wrapper_test.go
- test/integration/api/rest_api_test.go
Related to https://github.com/goharbor/harbor/issues/11544
Fresh install of the adapter service does not trigger
the Trivy DB download. In such case the metadata
response returns a misleading default datetime.
This commit skips returning the default datetime
when the Trivy DB update dates areno t available.
> fix: Do not show DB update dates when not available

- pkg/harbor/model.go
- pkg/harbor/model_test.go
- pkg/scan/controller_test.go
When registry URL is specified as internal address Trivy
cannot resolve image reference and is trying to pull the
image from index.docker.io
This commit adds port 80 or 433 if it's not specified
in the registry URL.
Resolves: #108
> fix: Append port to image reference

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile
- cmd/scanner-trivy/main.go
- pkg/queue/worker.go
- pkg/scan/controller_test.go
- test/component/component_test.go
This one solves also a subtle bug where we create a new Redis
connection pool for each scan job run.
Bumps up Trivy from v0.9.0 to v0.9.1.
> refactor: Inject dependencies to gocraft/work worker the right way

- .github/workflows/build.yml
> fix: Pin Trivy action image to 0.9.2

- pkg/http/api/v1/handler.go
- pkg/http/api/v1/handler_test.go
- test/integration/api/rest_api_test.go
This is a little change in the way we return custom metadata properties to display and troubleshoot various adapter settings, which are passed to the Trivy scanner.
Before
After
> feat: Return envs as metadata properties

- .github/workflows/build.yml
- .github/workflows/release.yml
- go.mod
Harbor 2.2 is still built with Go 1.14 because of the breaking change in Go 1.15.
- https://github.com/goharbor/harbor/pull/13326
- https://github.com/golang/go/issues/39568
> chore: Downgrade Go from 1.15 to 1.14

- Dockerfile
- go.mod
- go.sum
- pkg/harbor/model.go
- pkg/scan/transformer.go
- pkg/scan/transformer_test.go
- pkg/trivy/model.go
- test/component/component_test.go
> feat: Add Common Weakness Enumeration (CWE) identifiers to vulnerability report

- Dockerfile
- test/component/component_test.go
It would be great to release new version of adapter according to fresh Trivy release.
> Bump trivy to 0.17.2

- Dockerfile
- helm/harbor-scanner-trivy/values.yaml
Replacing user and group IDs 1000:1000 with 10000:10000
makes this adapter service "compatible" with core Harbor
componens.
> chore: Replace user and group IDs with 10000:10000

- Dockerfile
- test/component/component_test.go
Hey guys,
This micro-PR simply updates the version of Trivy bundled in the harbor adapter from 0.20.1 (Oct 2020) to the latest (0.22.0).
Cheers! :)
D
> Update Trivy to 0.22.0

- go.mod
- go.sum
bump golang.org/x/net fixing CVE-2022-27664
> chore: bump golang.org/x/net fixing CVE-2022-27664

- .github/workflows/build.yml
- cmd/scanner-trivy/main.go
- go.mod
- go.sum
- pkg/etc/checker.go
- pkg/etc/config.go
- pkg/etc/config_test.go
- pkg/http/api/base_handler.go
- pkg/http/api/server.go
- pkg/http/api/v1/handler.go
- pkg/persistence/redis/store.go
- pkg/queue/enqueuer.go
- pkg/queue/worker.go
- pkg/redisx/pool.go
- pkg/scan/controller.go
- pkg/scan/transformer.go
- pkg/trivy/wrapper.go
Go 1.21 added support for structured logging. It looks enough for our use case.
> refactor: replace logrus with slog

- .github/workflows/release.yml
chore: auto bump-go-version release
> chore: auto bump-go-version release

- .github/workflows/release.yml
chore: auto bump go-version release workflow
> chore: auto bump go-version release workflow

- Dockerfile
- README.md
- test/component/component_test.go
v0.48.3 contains several security fixes in dependencies.
> chore(deps): bump trivy to v0.48.3

- README.md
There is no option to select the Scanner in the Helm Chart, the default installation will install Trivy
> Remove Scanner reference in Helm install command
